name: dockerize
on:
  push:
    tags:
      - "*"
    branches:
      - main
    paths:
      - docker/**/*
  workflow_dispatch:
    inputs:
      tag:
        description: "Docker image tag"
        default: "dev"
      khoj:
        description: "Build Khoj docker image"
        type: boolean
        default: true
      khoj-cloud:
        description: "Build Khoj cloud docker image"
        type: boolean
        default: true
env:
  # Tag Image with tag name on release
  # else with user specified tag (default 'dev') if triggered via workflow
  # else with run_id if triggered via a pull request
  # else with 'pre' (if push to master)
  DOCKER_IMAGE_TAG: ${{ github.ref_type == 'tag' && github.ref_name || github.event_name == 'workflow_dispatch' && github.event.inputs.tag || 'pre' }}

# 并发控制(自动取消之前没完成的工作流)
# 方式 1: 取消进行中的工作流
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

# 方式 2: 更细粒度的控制，基于分支或其他条件
# concurrency:
#   group: ${{ github.workflow }}-${{ github.ref_name }}
#   cancel-in-progress: ${{ github.ref != 'refs/heads/main' }}

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USER }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          context: .
          push: true
          tags: ${{ secrets.DOCKERHUB_USER }}/gomtm:latest
          dockerfile: docker/base/Dockerfile
          target: mtmbase
