name: dockerize
on:
  push:
    tags:
      - "*"
    branches:
      - main
    paths:
      - docker/**/*
  workflow_dispatch:
    inputs:
      tag:
        description: "Docker image tag"
        default: "dev"
      khoj:
        description: "Build Khoj docker image"
        type: boolean
        default: true
      khoj-cloud:
        description: "Build Khoj cloud docker image"
        type: boolean
        default: true
env:
  # Tag Image with tag name on release
  # else with user specified tag (default 'dev') if triggered via workflow
  # else with run_id if triggered via a pull request
  # else with 'pre' (if push to master)
  DOCKER_IMAGE_TAG: ${{ github.ref_type == 'tag' && github.ref_name || github.event_name == 'workflow_dispatch' && github.event.inputs.tag || 'pre' }}

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ vars.gitgit188 }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          context: .
          push: true
          tags: gitgit188/gomtm:latest
          dockerfile: docker/gomtm/Dockerfile
          target: mtmbase
