name: build

on:
  push:
    branches: ["main"]
    paths:
      - mtmai/**/*

  pull_request:
    branches: ["main"]

  workflow_dispatch:
    inputs:
      tag:
        description: "Docker image tag"
        default: "dev"
      khoj:
        description: "Build Khoj docker image"
        type: boolean
        default: true
      khoj-cloud:
        description: "Build Khoj cloud docker image"
        type: boolean
        default: true


# 添加必要的权限
permissions:
  contents: write
  packages: write
  actions: write
  id-token: write

# 并发控制(自动取消之前没完成的工作流)
# 方式 1: 取消进行中的工作流
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  # main_route:
  #   runs-on: ubuntu-latest
  #   outputs:
  #     nextjob: ${{ steps.check_message.outputs.nextjob }}
  #   steps:
  #     - name: Check commit message
  #       id: check_message
  #       run: |
  #         message="${{ github.event.head_commit.message }}"
  #         if [[ $message =~ run_([^[:space:]]+) ]]; then
  #           echo "nextjob=${BASH_REMATCH[1]}" >> $GITHUB_OUTPUT
  #           echo "成功设置下一步: ${BASH_REMATCH[1]}"
  #         else
  #           echo "nextjob=none" >> $GITHUB_OUTPUT
  #           echo "未设置下一步"
  #         fi
  #       shell: bash
  #     - name: output_tag
  #       run: echo "LATEST_TAG=${{ env.LATEST_TAG }}" >> $GITHUB_OUTPUT

  debug_info:
    runs-on: ubuntu-latest
    steps:
      - name: Show routing info
        run: |
          echo "Commit message: ${{ github.event.head_commit.message }}"
          echo "Next job to run: ${{ needs.main_route.outputs.nextjob }}"

      - name: Show commit info
        run: |
          echo "Commit message: ${{ github.event.head_commit.message }}"
          echo "Commit author: ${{ github.event.head_commit.author.name }}"
          echo "Commit SHA: ${{ github.sha }}"

      - name: Show GitHub context
        run: echo "${{ toJSON(github) }}"

      - name: Show environment variables
        run: env


  mtmai_test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install a semver range of uv
        uses: astral-sh/setup-uv@v5
        with:
          version: ">=0.4.0"

      - uses: actions/setup-python@v5
        with:
          python-version: '3.13'
          enable-cache: true
          cache-dependency-glob: "**/pyproject.toml"

      - name: install python pyproject
        run: uv pip install -e .

      - name: run worker
        run: |
          python -m mtmai worker2


